SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM SHIPPINGS;

SELECT * 
FROM CUSTOMERS
WHERE FIRST_NAME = 'John'
AND LAST_NAME = 'Doe';

SELECT ITEM, COUNT(ITEM) AS quantity, SUM(AMOUNT) AS total
FROM ORDERS
GROUP BY ITEM
ORDER BY AMOUNT DESC;

SELECT SHIPPINGS.*, CUSTOMERS.COUNTRY
FROM SHIPPINGS
INNER JOIN CUSTOMERS
ON SHIPPINGS.CUSTOMER = CUSTOMERS.CUSTOMER_ID;

SELECT AVG(AGE) AS avg_age
FROM CUSTOMERS;

SELECT STATUS, COUNT(STATUS) as status_counts
FROM SHIPPINGS
GROUP BY STATUS
ORDER BY status_counts;
